import type { Metadata } from "next";
import localFont from "next/font/local";
import { EdgeStoreProvider } from "../lib/edgestore";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import QueryClientProvider from "./QueryClientProvider";
import { ReactNode } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen">{children}</body>
    </html>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      {/* Header */}
      <Header />

      <QueryClientProvider>
        {/* Main Content */}
        <main className="flex-grow bg-[#F6F8FA] max-w-screen-2xl mx-auto w-full overflow-y-auto">
          {children}
        </main>
      </QueryClientProvider>

      {/* Footer */}
      <Footer />
    </Layout>
  );
}
